//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:27:49 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AK1Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AK1Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MessageBody" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="SignCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="MessageID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Initiator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="SessionKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="CryptKeyID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AK1Request", propOrder = {
    "messageType",
    "messageBody",
    "signCertificate",
    "messageID",
    "initiator",
    "signature",
    "sessionKey",
    "cryptKeyID"
})
public class AK1Request {

    @XmlElement(name = "MessageType")
    protected String messageType;
    @XmlElement(name = "MessageBody")
    protected byte[] messageBody;
    @XmlElement(name = "SignCertificate")
    protected byte[] signCertificate;
    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "Initiator")
    protected String initiator;
    @XmlElement(name = "Signature")
    protected byte[] signature;
    @XmlElement(name = "SessionKey")
    protected byte[] sessionKey;
    @XmlElement(name = "CryptKeyID", required = true)
    protected String cryptKeyID;

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageBody property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMessageBody() {
        return messageBody;
    }

    /**
     * Sets the value of the messageBody property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMessageBody(byte[] value) {
        this.messageBody = value;
    }

    /**
     * Gets the value of the signCertificate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignCertificate() {
        return signCertificate;
    }

    /**
     * Sets the value of the signCertificate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignCertificate(byte[] value) {
        this.signCertificate = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the initiator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiator() {
        return initiator;
    }

    /**
     * Sets the value of the initiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiator(String value) {
        this.initiator = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignature(byte[] value) {
        this.signature = value;
    }

    /**
     * Gets the value of the sessionKey property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSessionKey() {
        return sessionKey;
    }

    /**
     * Sets the value of the sessionKey property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSessionKey(byte[] value) {
        this.sessionKey = value;
    }

    /**
     * Gets the value of the cryptKeyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptKeyID() {
        return cryptKeyID;
    }

    /**
     * Sets the value of the cryptKeyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptKeyID(String value) {
        this.cryptKeyID = value;
    }

}
