//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:27:49 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dkey.customs.soapmeta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dkey.customs.soapmeta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AskCustoms1 }
     * 
     */
    public AskCustoms1 createAskCustoms1() {
        return new AskCustoms1();
    }

    /**
     * Create an instance of {@link AK1Request }
     * 
     */
    public AK1Request createAK1Request() {
        return new AK1Request();
    }

    /**
     * Create an instance of {@link AskCustoms1Response }
     * 
     */
    public AskCustoms1Response createAskCustoms1Response() {
        return new AskCustoms1Response();
    }

    /**
     * Create an instance of {@link AK1Response }
     * 
     */
    public AK1Response createAK1Response() {
        return new AK1Response();
    }

    /**
     * Create an instance of {@link UploadImfx1 }
     * 
     */
    public UploadImfx1 createUploadImfx1() {
        return new UploadImfx1();
    }

    /**
     * Create an instance of {@link UI1Request }
     * 
     */
    public UI1Request createUI1Request() {
        return new UI1Request();
    }

    /**
     * Create an instance of {@link UploadImfx1Response }
     * 
     */
    public UploadImfx1Response createUploadImfx1Response() {
        return new UploadImfx1Response();
    }

    /**
     * Create an instance of {@link UI1Response }
     * 
     */
    public UI1Response createUI1Response() {
        return new UI1Response();
    }

    /**
     * Create an instance of {@link DownloadImfx1 }
     * 
     */
    public DownloadImfx1 createDownloadImfx1() {
        return new DownloadImfx1();
    }

    /**
     * Create an instance of {@link DI1Request }
     * 
     */
    public DI1Request createDI1Request() {
        return new DI1Request();
    }

    /**
     * Create an instance of {@link DownloadImfx1Response }
     * 
     */
    public DownloadImfx1Response createDownloadImfx1Response() {
        return new DownloadImfx1Response();
    }

    /**
     * Create an instance of {@link DI1Response }
     * 
     */
    public DI1Response createDI1Response() {
        return new DI1Response();
    }

    /**
     * Create an instance of {@link GetCurRates }
     * 
     */
    public GetCurRates createGetCurRates() {
        return new GetCurRates();
    }

    /**
     * Create an instance of {@link GetRateRequest }
     * 
     */
    public GetRateRequest createGetRateRequest() {
        return new GetRateRequest();
    }

    /**
     * Create an instance of {@link GetCurRatesResponse }
     * 
     */
    public GetCurRatesResponse createGetCurRatesResponse() {
        return new GetCurRatesResponse();
    }

    /**
     * Create an instance of {@link GetRateResponse }
     * 
     */
    public GetRateResponse createGetRateResponse() {
        return new GetRateResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRate }
     * 
     */
    public ArrayOfRate createArrayOfRate() {
        return new ArrayOfRate();
    }

    /**
     * Create an instance of {@link Rate }
     * 
     */
    public Rate createRate() {
        return new Rate();
    }

}
